<?xml version="1.0"?>
<package format="3">
<name>scara_robot</name>
<version>1.0.0</version>
<description>Robot SCARA para proyecto final</description>
<maintainer email="alumno@robotica.com">Alumno</maintainer>
<license>MIT</license>

<depend>rclpy</depend>
<depend>std_msgs</depend>
<depend>sensor_msgs</depend>
<depend>robot_state_publisher</depend>
<depend>joint_state_publisher_gui</depend>
<depend>rviz2</depend>

<export>
<build_type>ament_python</build_type>
</export>
</package>